apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ts-commons
  namespace: default
spec:
  hosts:
    - ts-commons
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: gateway-error,connect-failure,retriable-4xx
      route:
        - destination:
            host: ts-commons
            port:
              number: 3000
          weight: 100
