apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ts-commons.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ts-commons.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
