apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml

images:
  - name: ts-commons
    newTag: latest

configMapGenerator:
  - name: ts-commons-config
    behavior: merge
    literals:
      - LOG_LEVEL=warn
      - METRICS_ENABLED=true
      - TRACING_ENABLED=true
