apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ts-commons-kong-ingress
  namespace: default
  annotations:
    konghq.com/plugins: ts-commons-rate-limit,ts-commons-key-auth,ts-commons-request-transform
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /v1/ts-commons
            pathType: Prefix
            backend:
              service:
                name: ts-commons
                port:
                  number: 3000
