apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ts-commons-key-auth
  namespace: default
plugin: key-auth
config:
  key_names:
    - X-Api-Key
  key_in_header: true
  key_in_query: false
  key_in_body: false
  hide_credentials: true
